  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
sudo: required

language: java
jdk: oraclejdk8

install: true

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods se_methods